dist: trusty
sudo: required
language: generic
services:
  - docker

matrix:
  include:
  - env: GHCVER=8.0.2 CABALVER=1.24 STACKVER=1.6.5
  - env: GHCVER=8.2.2 CABALVER=1.24 STACKVER=1.6.5
  - env: GHCVER=8.4.2 CABALVER=1.24 STACKVER=1.6.5

script:
  - travis_wait 90 bin/ci

notifications:
  slack:
    secure: fZ4I6Z03cIljDrKbSwV/9wyujVyPrAR5Lx3sXrM7coXPzlDyiP1haJRH4PLbXQW96lHfKh4uDZd2hlmwoSkPbs8ETMbuHGXj8zgF492iZPimklVK/cG5cGK+D5yq8Rh6bbKZ+5TR5Isz0Wlc3Mjs4YfXD8zMd8klV0QlMHg9hqNpuj2sYvzR1m1TLenTVtC7YQDU1NNo6vIEkqbvV1Z1Faotp45uVOiC7N/hfg6cdaHdJHZgmnaEbR3mdtRsFkcdvkRUTSZTI8RhTBUUzJ/EUpi2U4SpcQGCfWl3g7LD5bYPaE1AT2uLaf7YqA2FRA9XVQBZOzh/u7r2Xm1Q8Fc/2TkFZAqk2UN5sgET/hUG3HikNWE18r71KmNOp6tiEGfOljweSQSqWEB+/fc7IGNTGh4QpeVcIc1dmUhJeSYJn2HMY9sSFBRzeU4ewzgrs5BIJ1/cH28ECnP/+C0/c+gdsMxWg9xI7IEnHQP4cnlUuFytFWAvDM9v7NfCYoJ/K0Oux4C8Beb3ZuMNWxeBXGfY95P5i9hZsKKFb94V0Icq5wVjzWdP2YGAucmRZxOWPrb6eKYsPwc0Bwzxt4othVodNsBDp8KoLKc2SXTzIzuJ6rSj3jSx5AZlatoij2TSpmmjWHZpa3pAOoHLYHK4ale7HLZOzm+1glru1dxR5obbRas=
